name: Sync to Gitee Mirror

# 触发条件：main分支推送时自动同步
on:
  push:
    branches: [ main ]

  # 支持手动触发同步
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Sync GitHub repo to Gitee
        uses: wearerequired/git-mirror-action@v1
        with:
          # 源地址：自动获取当前GitHub仓库地址
          source-repo: https://github.com/${{ github.repository }}.git
          # 目标地址：直接读取我们配置好的完整带令牌地址
          destination-repo: ${{ secrets.GITEE_FULL_URL }}
